"""Deterministic stage-window policy generated by the analytical MoE model."""

from __future__ import annotations

import hashlib
import json
import math
from dataclasses import asdict, dataclass
from functools import lru_cache

try:
    from weight_window import achievable_worker_windows
except ImportError:  # pragma: no cover - package-style import
    from .weight_window import achievable_worker_windows


INHERIT_STAGE_WINDOW = -1
POLICY_VERSION = 2


@dataclass(frozen=True)
class AnalyticStageWindowDecision:
    routes: int
    threads: int
    w13_target_bytes: int
    w2_target_bytes: int
    w13_worker_bytes: int
    w2_worker_bytes: int
    w13_ranges: int
    w2_ranges: int


class AnalyticStageWindowPolicy:
    """Generate one window pair from cache geometry and ECM service demand.

    This policy is not an additional planner variable. For a fixed analytical
    model, route count and team width it deterministically minimizes the model's
    stage-local incremental objective, then lowers the result to the existing
    per-range byte ABI.
    """

    def __init__(self, model) -> None:
        self.model = model
        identity = {
            "version": POLICY_VERSION,
            "machine": model.calibration.to_dict(),
            "hidden_size": model.hidden_size,
            "intermediate_size": model.intermediate_size,
            "backend_n_tile": model.policy.backend_n_tile,
            "w13_split_chunks": model.w13_split_chunks,
            "supported_widths": model.supported_widths,
        }
        digest = hashlib.sha256(
            json.dumps(identity, sort_keys=True, separators=(",", ":")).encode("utf-8")
        ).hexdigest()[:12]
        self.name = f"analytic_stage_window_v{POLICY_VERSION}:{model.calibration.machine_id}:{digest}"

    @staticmethod
    def _is_power_of_two(value: int) -> bool:
        return value > 0 and value & (value - 1) == 0

    def _stage_geometry(self, stage: str) -> tuple[int, int, int, int, int]:
        if stage == "w13":
            return (
                self.model.hidden_size,
                2 * self.model.intermediate_size,
                self.model.w13_split_chunks,
                self.model._w13_geometry.ranges,
                self.model._w13_geometry.max_range_bytes,
            )
        if stage == "w2":
            return (
                self.model.intermediate_size,
                self.model.hidden_size,
                1,
                self.model._w2_geometry.ranges,
                self.model._w2_geometry.max_range_bytes,
            )
        raise ValueError(f"unsupported stage {stage!r}")

    @lru_cache(maxsize=4096)
    def _stage_candidates(self, stage: str, routes: int, threads: int):
        k, n, minimum_ranges, inherited_ranges, inherited_range_bytes = self._stage_geometry(stage)
        tile_bytes = k * self.model.policy.backend_n_tile * 2
        total_tiles = n // self.model.policy.backend_n_tile
        geometries = achievable_worker_windows(
            k=k,
            n=n,
            n_tile=self.model.policy.backend_n_tile,
            threads=threads,
        )
        targets: set[int] = {inherited_range_bytes}
        for worker_bytes, (ranges, range_bytes) in geometries.items():
            worker_tiles = worker_bytes // tile_bytes
            range_tiles = range_bytes // tile_bytes
            if ranges < minimum_ranges:
                continue
            # Once the owner stripe is below one private L1D there is no lower
            # cache level left to protect. More ranges can only add control and
            # synchronization, so such points are analytically dominated even
            # when a calibration has a zero range-fixed term.
            if worker_bytes < self.model.calibration.caches.l1d_bytes_per_core:
                continue
            if range_tiles < min(threads, total_tiles):
                continue
            if self._is_power_of_two(worker_tiles):
                targets.add(range_bytes)

        legal_scores = []
        for target in sorted(targets):
            score = self.model.score_stage_window(stage, routes, threads, target)
            if score.ranges >= minimum_ranges:
                legal_scores.append(score)
        scores = tuple(legal_scores)
        if not scores:
            raise RuntimeError(f"no legal analytical {stage} stage-window candidate at {threads} threads")
        minimum = min(scores, key=lambda score: (score.objective_ns, -score.worker_bytes, score.ranges))
        objective_resolution_ns = self.model.calibration.relative_uncertainty * minimum.transfer_ns
        equivalent = tuple(
            score for score in scores if score.objective_ns <= minimum.objective_ns + objective_resolution_ns
        )
        preferred_worker_bytes = max(
            self.model.calibration.caches.l1d_bytes_per_core,
            2 * tile_bytes,
        )
        selected = min(
            equivalent,
            key=lambda score: (
                abs(math.log2(score.worker_bytes / preferred_worker_bytes)),
                score.objective_ns,
                score.ranges,
            ),
        )
        inherited = next(
            (
                score
                for score in scores
                if score.ranges == inherited_ranges and score.range_bytes == inherited_range_bytes
            ),
            None,
        )
        return scores, selected, inherited

    @lru_cache(maxsize=4096)
    def decision(self, routes: int, threads: int) -> AnalyticStageWindowDecision:
        routes = int(routes)
        threads = int(threads)
        if routes <= 0 or threads <= 0:
            raise ValueError("routes and threads must be positive")
        if threads not in self.model.supported_widths:
            raise KeyError(f"unsupported analytical thread width {threads}")
        if routes <= 12:
            return AnalyticStageWindowDecision(
                routes=routes,
                threads=threads,
                w13_target_bytes=INHERIT_STAGE_WINDOW,
                w2_target_bytes=INHERIT_STAGE_WINDOW,
                w13_worker_bytes=self.model._w13_geometry.bytes_per_worker(threads),
                w2_worker_bytes=self.model._w2_geometry.bytes_per_worker(threads),
                w13_ranges=self.model._w13_geometry.ranges,
                w2_ranges=self.model._w2_geometry.ranges,
            )

        _, w13, inherited_w13 = self._stage_candidates("w13", routes, threads)
        _, w2, inherited_w2 = self._stage_candidates("w2", routes, threads)
        w13_target = (
            INHERIT_STAGE_WINDOW
            if inherited_w13 is not None and w13.range_bytes == inherited_w13.range_bytes
            else w13.range_bytes
        )
        w2_target = (
            INHERIT_STAGE_WINDOW
            if inherited_w2 is not None and w2.range_bytes == inherited_w2.range_bytes
            else w2.range_bytes
        )
        return AnalyticStageWindowDecision(
            routes=routes,
            threads=threads,
            w13_target_bytes=w13_target,
            w2_target_bytes=w2_target,
            w13_worker_bytes=w13.worker_bytes,
            w2_worker_bytes=w2.worker_bytes,
            w13_ranges=w13.ranges,
            w2_ranges=w2.ranges,
        )

    def select(self, routes: int, threads: int) -> tuple[int, int]:
        decision = self.decision(int(routes), int(threads))
        return decision.w13_target_bytes, decision.w2_target_bytes

    def worker_windows(self, routes: int, threads: int) -> tuple[int, int]:
        decision = self.decision(int(routes), int(threads))
        return decision.w13_worker_bytes, decision.w2_worker_bytes

    def explain(self, routes: int, threads: int) -> dict:
        decision = self.decision(int(routes), int(threads))
        payload = {
            "policy": self.name,
            "decision": asdict(decision),
            "reason": (
                "single_m12_panel_inherits"
                if routes <= 12
                else "uncertainty_robust_incremental_ecm_objective"
            ),
            "candidates": {},
        }
        for stage in ("w13", "w2"):
            scores, selected, inherited = self._stage_candidates(stage, int(routes), int(threads))
            minimum = min(
                scores,
                key=lambda score: (score.objective_ns, -score.worker_bytes, score.ranges),
            )
            tile_bytes = self.model.w13_tile_bytes if stage == "w13" else self.model.w2_tile_bytes
            payload["candidates"][stage] = {
                "selected_range_bytes": selected.range_bytes,
                "inherited_range_bytes": inherited.range_bytes if inherited is not None else None,
                "minimum_objective_ns": minimum.objective_ns,
                "objective_resolution_ns": (
                    self.model.calibration.relative_uncertainty * minimum.transfer_ns
                ),
                "preferred_worker_bytes": max(
                    self.model.calibration.caches.l1d_bytes_per_core,
                    2 * tile_bytes,
                ),
                "rows": [asdict(score) for score in scores],
            }
        return payload

    def cost_model_entries(self) -> tuple[object, ...]:
        """The mapping is formula-generated and intentionally has no finite table."""
        return ()


__all__ = [
    "AnalyticStageWindowDecision",
    "AnalyticStageWindowPolicy",
    "POLICY_VERSION",
]
