# -*- coding: utf-8 -*-
"""fused-cpp: CPU Fused MLA and MoE implementations (pure PyTorch)."""

from fused_cpp.acl_gemm import (
    ACLGEMMHandler,
    _supports_acl,
    acl_gemm,
    create_acl_gemm,
    get_acl_affinity,
    set_acl_affinity,
)
from fused_cpp.kai_gemm import (
    KAIGEMMHandler,
    KAIThreadPool,
    _supports_kai,
    create_kai_gemm,
    kai_gemm,
    kai_gemm_prepare,
)
from . import i8gemm
from . import bf16_linear
from fused_cpp.bf16_linear import (
    PreparedBF16LinearWeight,
    _supports_bf16_linear,
    linear as bf16_linear_mm,
    linear_raw as bf16_linear_raw,
    prepare as prepare_bf16_linear_weight,
)
from fused_cpp.i8gemm import PreparedI8GEMMWeight, _supports_i8gemm
from fused_cpp.mla import CPUFusedMLAImpl
from fused_cpp.mla.impl import _HAS_CPP
from fused_cpp.moe import (
    AWQFusedMoEImpl,
    FusedMoEImpl,
    PreparedBF16TiledFusedMoEWeights,
    _HAS_BF16_TILED_FUSED_MOE,
    available_fused_moe_bf16_tiled_backends,
    fused_moe_bf16_tiled,
    fused_moe_bf16_tiled_scheduled,
    fused_moe_bf16_tiled_async,
    fused_moe_bf16_tiled_vllm_staged,
    fused_moe_naive,
    bf16_tiled_fused_moe,
    bf16_tiled_fused_moe_scheduled,
    bf16_tiled_fused_moe_async,
    bf16_tiled_fused_moe_vllm_staged,
    naive_fused_moe,
    prepare_fused_moe_bf16_tiled_weights,
    prepare_bf16_tiled_fused_moe_weights,
)
from fused_cpp.mqa import multi_query_attention, multi_query_attention_torch
from fused_cpp.deepseek_v4_attn_gemm_fused import (
    PreparedDeepSeekV4AttnGemmWeights,
    PreparedWeight,
    _HAS_DEEPSEEK_V4_ATTN_GEMM_FUSED,
    deepseek_v4_attn_gemm_fused_prepacked,
    deepseek_v4_attn_gemm_fused_prepacked_normed,
    fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused,
    fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_mt,
    fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_prepare,
    fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_prepare_weights,
    fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_prepacked,
    fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_qkv_rmsnorm_fused_prepacked,
    prepare_deepseek_v4_attn_gemm_weights,
)
from fused_cpp.deepseek_v4_post_gemm_stage import (
    CompressorState,
    PostGemmStageInputs,
    PostGemmStageVariant,
    PreparedDeepSeekV4PostGemmWeights,
    SWACacheState,
    SparseIndexerPrefillMetadata,
    _HAS_DEEPSEEK_V4_POST_GEMM_C128A_PREPACKED,
    _HAS_DEEPSEEK_V4_POST_GEMM_DENSE_PREPACKED,
    _HAS_DEEPSEEK_V4_POST_GEMM_STAGE,
    _HAS_DEEPSEEK_V4_POST_GEMM_STAGE_PREPACKED,
    post_gemm_parallel_stage,
    post_gemm_parallel_stage_cpp,
    post_gemm_parallel_stage_cpp_prepacked,
    post_gemm_parallel_stage_torch_baseline,
    prepare_deepseek_v4_post_gemm_weights,
)
from fused_cpp.deepseek_v4_prefill_cache import (
    _HAS_DEEPSEEK_V4_PREFILL_CACHE_OPS,
    combine_topk_swa_indices_cpp,
    combine_topk_swa_indices_torch_baseline,
    dequantize_and_gather_dual_k_cache_cpp,
    dequantize_and_gather_dual_k_cache_torch_baseline,
    dequantize_and_gather_k_cache_cpp,
    dequantize_and_gather_k_cache_torch_baseline,
)
from fused_cpp.sdpa import (
    VersionInfo,
    available_sdpa_versions,
    get_sdpa_version,
    register_sdpa_version,
    scaled_dot_product_attention,
    sdpa_versioned,
)
from fused_cpp.sparse_mla import (
    flash_mla_sparse_fwd,
    flash_mla_sparse_fwd_naive,
    sparse_mla,
    sparse_mla_naive,
)
from fused_cpp.sparse_attn_indexer import (
    _HAS_CPP_SPARSE_ATTN_INDEXER,
    available_sparse_attn_indexer_versions,
    cpu_sparse_attn_indexer_op,
    cpu_sparse_attn_indexer_op_cpp_v0,
    cpu_sparse_attn_indexer_op_torch_baseline,
    sparse_attn_indexer_op,
)
from fused_cpp.w4a8_linear import (
    unpack_awq_qweight,
    unpack_awq_qzeros,
    w4a8_linear,
)


def has_cpp_kernels() -> bool:
    """Return True if C++ extension is available."""
    return _HAS_CPP


BACKEND: str = "cpp" if _HAS_CPP else "pytorch"

__all__ = [
    "ACLGEMMHandler",
    "AWQFusedMoEImpl",
    "BACKEND",
    "CPUFusedMLAImpl",
    "FusedMoEImpl",
    "KAIGEMMHandler",
    "KAIThreadPool",
    "PreparedDeepSeekV4AttnGemmWeights",
    "PreparedDeepSeekV4PostGemmWeights",
    "PreparedBF16TiledFusedMoEWeights",
    "PreparedBF16LinearWeight",
    "PreparedI8GEMMWeight",
    "PreparedWeight",
    "PostGemmStageInputs",
    "SWACacheState",
    "SparseIndexerPrefillMetadata",
    "CompressorState",
    "VersionInfo",
    "_HAS_DEEPSEEK_V4_ATTN_GEMM_FUSED",
    "_HAS_BF16_TILED_FUSED_MOE",
    "available_fused_moe_bf16_tiled_backends",
    "_HAS_DEEPSEEK_V4_POST_GEMM_STAGE",
    "_HAS_DEEPSEEK_V4_POST_GEMM_STAGE_PREPACKED",
    "_HAS_DEEPSEEK_V4_PREFILL_CACHE_OPS",
    "_HAS_CPP_SPARSE_ATTN_INDEXER",
    "_supports_acl",
    "_supports_i8gemm",
    "_supports_bf16_linear",
    "_supports_kai",
    "acl_gemm",
    "available_sdpa_versions",
    "available_sparse_attn_indexer_versions",
    "create_acl_gemm",
    "create_kai_gemm",
    "combine_topk_swa_indices_cpp",
    "combine_topk_swa_indices_torch_baseline",
    "cpu_sparse_attn_indexer_op",
    "cpu_sparse_attn_indexer_op_cpp_v0",
    "cpu_sparse_attn_indexer_op_torch_baseline",
    "deepseek_v4_attn_gemm_fused_prepacked",
    "deepseek_v4_attn_gemm_fused_prepacked_normed",
    "dequantize_and_gather_dual_k_cache_cpp",
    "dequantize_and_gather_dual_k_cache_torch_baseline",
    "dequantize_and_gather_k_cache_cpp",
    "dequantize_and_gather_k_cache_torch_baseline",
    "flash_mla_sparse_fwd",
    "flash_mla_sparse_fwd_naive",
    "fused_moe_bf16_tiled",
    "fused_moe_bf16_tiled_scheduled",
    "fused_moe_bf16_tiled_async",
    "fused_moe_bf16_tiled_vllm_staged",
    "fused_moe_naive",
    "fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused",
    "fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_mt",
    "fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_prepare",
    "fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_prepare_weights",
    "fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_prepacked",
    "fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_qkv_rmsnorm_fused_prepacked",
    "get_acl_affinity",
    "get_sdpa_version",
    "bf16_tiled_fused_moe",
    "bf16_tiled_fused_moe_scheduled",
    "bf16_tiled_fused_moe_async",
    "bf16_tiled_fused_moe_vllm_staged",
    "bf16_linear",
    "bf16_linear_mm",
    "bf16_linear_raw",
    "has_cpp_kernels",
    "i8gemm",
    "kai_gemm",
    "kai_gemm_prepare",
    "multi_query_attention",
    "multi_query_attention_torch",
    "naive_fused_moe",
    "prepare_deepseek_v4_attn_gemm_weights",
    "prepare_bf16_linear_weight",
    "PostGemmStageVariant",
    "_HAS_DEEPSEEK_V4_POST_GEMM_C128A_PREPACKED",
    "_HAS_DEEPSEEK_V4_POST_GEMM_DENSE_PREPACKED",
    "post_gemm_parallel_stage",
    "post_gemm_parallel_stage_cpp",
    "post_gemm_parallel_stage_cpp_prepacked",
    "post_gemm_parallel_stage_torch_baseline",
    "prepare_deepseek_v4_post_gemm_weights",
    "prepare_fused_moe_bf16_tiled_weights",
    "prepare_bf16_tiled_fused_moe_weights",
    "register_sdpa_version",
    "scaled_dot_product_attention",
    "sdpa_versioned",
    "set_acl_affinity",
    "sparse_attn_indexer_op",
    "sparse_mla",
    "sparse_mla_naive",
    "unpack_awq_qweight",
    "unpack_awq_qzeros",
    "w4a8_linear",
]
