# -*- coding: utf-8 -*-
"""fused-cpp: CPU Fused MLA and MoE implementations (pure PyTorch)."""

from fused_cpp.acl_gemm import (
    ACLGEMMHandler,
    _supports_acl,
    acl_gemm,
    create_acl_gemm,
    get_acl_affinity,
    set_acl_affinity,
)
from fused_cpp.kai_gemm import (
    KAIGEMMHandler,
    KAIThreadPool,
    _supports_kai,
    create_kai_gemm,
    kai_gemm,
    kai_gemm_prepare,
)
from . import i8gemm
from . import bf16_linear
from fused_cpp.bf16_linear import (
    PreparedBF16LinearWeight,
    _supports_bf16_linear,
    linear as bf16_linear_mm,
    linear_raw as bf16_linear_raw,
    prepare as prepare_bf16_linear_weight,
)
from fused_cpp.i8gemm import PreparedI8GEMMWeight, _supports_i8gemm
from fused_cpp.mla import CPUFusedMLAImpl
from fused_cpp.mla.impl import _HAS_CPP
from fused_cpp.moe import (
    ASYNC_MOE_EXECUTION_STRICT,
    ASYNC_MOE_EXECUTION_TAIL_POOL,
    ASYNC_MOE_FULL_EXPERT_RANGE,
    ASYNC_MOE_PLACEMENT_FIXED,
    ASYNC_MOE_PLACEMENT_TAIL_POOL,
    ASYNC_MOE_PLAN_VERSION,
    ASYNC_MOE_RESIZE_NONE,
    ASYNC_MOE_STAGE_EXPERT,
    AWQFusedMoEImpl,
    AsyncMoEPlanV2,
    DEFAULT_MOE_COST_CACHE_DIR,
    FusedMoEImpl,
    MoePlannerRuntime,
    PreparedBF16TiledFusedMoEWeights,
    PreparedBF16TiledRoutedSharedMoEWeights,
    PreparedW8A16TiledFusedMoEWeights,
    PreparedW8A8TiledFusedMoEWeights,
    PreparedW8A16TiledRoutedSharedMoEWeights,
    _HAS_BF16_TILED_FUSED_MOE,
    _HAS_W8A8_TILED_FUSED_MOE,
    available_fused_moe_bf16_tiled_backends,
    calibrate_moe_planner_quick,
    enable_moe_planner_quick,
    fused_moe_bf16_tiled,
    fused_moe_bf16_tiled_with_shared,
    fused_moe_bf16_tiled_scheduled,
    fused_moe_bf16_tiled_async,
    fused_moe_bf16_tiled_async_plan,
    fused_moe_bf16_tiled_planned_staged,
    fused_moe_bf16_tiled_vllm_staged,
    fused_moe_tiled,
    fused_moe_w8a16_tiled,
    fused_moe_w8a16_tiled_async_plan,
    fused_moe_w8a8_tiled,
    fused_moe_w8a8_tiled_async_plan,
    fused_moe_w8a16_tiled_with_shared,
    shared_mlp_bf16_tiled,
    fused_moe_naive,
    get_default_moe_planner_runtime,
    bf16_tiled_fused_moe,
    bf16_tiled_fused_moe_scheduled,
    bf16_tiled_fused_moe_async,
    bf16_tiled_fused_moe_async_plan,
    bf16_tiled_fused_moe_planned_staged,
    bf16_tiled_fused_moe_vllm_staged,
    naive_fused_moe,
    prepare_fused_moe_bf16_tiled_weights,
    prepare_fused_moe_w8a16_tiled_weights,
    prepare_fused_moe_w8a16_tiled_quantized_weights,
    prepare_fused_moe_w8a8_tiled_weights,
    prepare_fused_moe_w8a8_tiled_quantized_weights,
    prepare_routed_shared_moe_bf16_tiled_weights,
    prepare_routed_shared_moe_w8a16_tiled_quantized_weights,
    prepare_shared_mlp_bf16_tiled_weights,
    prepare_bf16_tiled_fused_moe_weights,
    set_default_moe_planner_runtime,
    upgrade_legacy_async_plan,
)
from fused_cpp.mqa import multi_query_attention, multi_query_attention_torch
from fused_cpp.deepseek_v4_attn_gemm_fused import (
    PreparedDeepSeekV4AttnGemmWeights,
    PreparedWeight,
    _HAS_DEEPSEEK_V4_ATTN_GEMM_FUSED,
    deepseek_v4_attn_gemm_fused_prepacked,
    deepseek_v4_attn_gemm_fused_prepacked_normed,
    fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused,
    fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_mt,
    fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_prepare,
    fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_prepare_weights,
    fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_prepacked,
    fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_qkv_rmsnorm_fused_prepacked,
    prepare_deepseek_v4_attn_gemm_weights,
)
from fused_cpp.deepseek_v4_inv_rope_woa import (
    PreparedDeepseekV4InvRopeWoa,
    _HAS_DEEPSEEK_V4_INV_ROPE_WOA,
    deepseek_v4_inv_rope_grouped_woa,
    deepseek_v4_inv_rope_grouped_woa_torch_reference,
    prepare_deepseek_v4_inv_rope_woa,
)
from fused_cpp.deepseek_v4_post_gemm_stage import (
    CompressorState,
    PostGemmStageInputs,
    PostGemmStageVariant,
    PreparedDeepSeekV4PostGemmWeights,
    PreparedDeepSeekV4PostGemmW8A8Weights,
    SWACacheState,
    SparseIndexerPrefillMetadata,
    _HAS_DEEPSEEK_V4_POST_GEMM_C128A_PREPACKED,
    _HAS_DEEPSEEK_V4_POST_GEMM_DENSE_PREPACKED,
    _HAS_DEEPSEEK_V4_POST_GEMM_STAGE,
    _HAS_DEEPSEEK_V4_POST_GEMM_STAGE_PREPACKED,
    post_gemm_parallel_stage,
    post_gemm_parallel_stage_cpp,
    post_gemm_parallel_stage_cpp_prepacked,
    post_gemm_parallel_stage_torch_baseline,
    prepare_deepseek_v4_post_gemm_weights,
    prepare_deepseek_v4_post_gemm_w8a8_quantized_weights,
    prepare_deepseek_v4_post_gemm_w8a8_weights,
)
from fused_cpp.deepseek_v4_w8a8 import (
    PreparedDeepSeekV4W8A8LinearWeight,
    _HAS_DEEPSEEK_V4_W8A8,
    deepseek_v4_w8a8_linear,
    deepseek_v4_w8a8_linear_pair,
    deepseek_v4_wo_b_w8a8,
    prepare_deepseek_v4_w8a8_linear_quantized_weight,
    prepare_deepseek_v4_w8a8_linear_weight,
)
from fused_cpp.deepseek_v4_prefill_cache import (
    _HAS_DEEPSEEK_V4_PREFILL_CACHE_OPS,
    combine_topk_swa_indices_cpp,
    combine_topk_swa_indices_torch_baseline,
    dequantize_and_gather_dual_k_cache_cpp,
    dequantize_and_gather_dual_k_cache_torch_baseline,
    dequantize_and_gather_k_cache_cpp,
    dequantize_and_gather_k_cache_torch_baseline,
)
from fused_cpp.sdpa import (
    VersionInfo,
    available_sdpa_versions,
    get_sdpa_version,
    register_sdpa_version,
    scaled_dot_product_attention,
    sdpa_versioned,
)
from fused_cpp.sparse_mla import (
    flash_mla_sparse_fwd,
    flash_mla_sparse_fwd_naive,
    sparse_mla,
    sparse_mla_naive,
)
from fused_cpp.sparse_attn_indexer import (
    _HAS_CPP_SPARSE_ATTN_INDEXER,
    available_sparse_attn_indexer_versions,
    cpu_sparse_attn_indexer_op,
    cpu_sparse_attn_indexer_op_cpp_v0,
    cpu_sparse_attn_indexer_op_torch_baseline,
    sparse_attn_indexer_op,
)
from fused_cpp.w4a8_linear import (
    unpack_awq_qweight,
    unpack_awq_qzeros,
    w4a8_linear,
)


def has_cpp_kernels() -> bool:
    """Return True if C++ extension is available."""
    return _HAS_CPP


BACKEND: str = "cpp" if _HAS_CPP else "pytorch"

__all__ = [
    "ACLGEMMHandler",
    "ASYNC_MOE_EXECUTION_STRICT",
    "ASYNC_MOE_EXECUTION_TAIL_POOL",
    "ASYNC_MOE_FULL_EXPERT_RANGE",
    "ASYNC_MOE_PLACEMENT_FIXED",
    "ASYNC_MOE_PLACEMENT_TAIL_POOL",
    "ASYNC_MOE_PLAN_VERSION",
    "ASYNC_MOE_RESIZE_NONE",
    "ASYNC_MOE_STAGE_EXPERT",
    "AWQFusedMoEImpl",
    "AsyncMoEPlanV2",
    "BACKEND",
    "CPUFusedMLAImpl",
    "DEFAULT_MOE_COST_CACHE_DIR",
    "FusedMoEImpl",
    "MoePlannerRuntime",
    "KAIGEMMHandler",
    "KAIThreadPool",
    "PreparedDeepSeekV4AttnGemmWeights",
    "PreparedDeepseekV4InvRopeWoa",
    "PreparedDeepSeekV4PostGemmWeights",
    "PreparedBF16TiledFusedMoEWeights",
    "PreparedBF16TiledRoutedSharedMoEWeights",
    "PreparedW8A16TiledFusedMoEWeights",
    "PreparedW8A8TiledFusedMoEWeights",
    "PreparedW8A16TiledRoutedSharedMoEWeights",
    "PreparedBF16LinearWeight",
    "PreparedI8GEMMWeight",
    "PreparedWeight",
    "PostGemmStageInputs",
    "SWACacheState",
    "SparseIndexerPrefillMetadata",
    "CompressorState",
    "VersionInfo",
    "_HAS_DEEPSEEK_V4_ATTN_GEMM_FUSED",
    "_HAS_DEEPSEEK_V4_INV_ROPE_WOA",
    "_HAS_BF16_TILED_FUSED_MOE",
    "_HAS_W8A8_TILED_FUSED_MOE",
    "available_fused_moe_bf16_tiled_backends",
    "calibrate_moe_planner_quick",
    "enable_moe_planner_quick",
    "_HAS_DEEPSEEK_V4_POST_GEMM_STAGE",
    "_HAS_DEEPSEEK_V4_POST_GEMM_STAGE_PREPACKED",
    "_HAS_DEEPSEEK_V4_PREFILL_CACHE_OPS",
    "_HAS_CPP_SPARSE_ATTN_INDEXER",
    "_supports_acl",
    "_supports_i8gemm",
    "_supports_bf16_linear",
    "_supports_kai",
    "acl_gemm",
    "available_sdpa_versions",
    "available_sparse_attn_indexer_versions",
    "create_acl_gemm",
    "create_kai_gemm",
    "combine_topk_swa_indices_cpp",
    "combine_topk_swa_indices_torch_baseline",
    "cpu_sparse_attn_indexer_op",
    "cpu_sparse_attn_indexer_op_cpp_v0",
    "cpu_sparse_attn_indexer_op_torch_baseline",
    "deepseek_v4_attn_gemm_fused_prepacked",
    "deepseek_v4_attn_gemm_fused_prepacked_normed",
    "deepseek_v4_inv_rope_grouped_woa",
    "deepseek_v4_inv_rope_grouped_woa_torch_reference",
    "dequantize_and_gather_dual_k_cache_cpp",
    "dequantize_and_gather_dual_k_cache_torch_baseline",
    "dequantize_and_gather_k_cache_cpp",
    "dequantize_and_gather_k_cache_torch_baseline",
    "flash_mla_sparse_fwd",
    "flash_mla_sparse_fwd_naive",
    "fused_moe_bf16_tiled",
    "fused_moe_bf16_tiled_with_shared",
    "fused_moe_bf16_tiled_scheduled",
    "fused_moe_bf16_tiled_async",
    "fused_moe_bf16_tiled_async_plan",
    "fused_moe_bf16_tiled_planned_staged",
    "fused_moe_bf16_tiled_vllm_staged",
    "fused_moe_tiled",
    "fused_moe_w8a16_tiled",
    "fused_moe_w8a16_tiled_async_plan",
    "fused_moe_w8a8_tiled",
    "fused_moe_w8a8_tiled_async_plan",
    "fused_moe_w8a16_tiled_with_shared",
    "shared_mlp_bf16_tiled",
    "fused_moe_naive",
    "get_default_moe_planner_runtime",
    "fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused",
    "fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_mt",
    "fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_prepare",
    "fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_prepare_weights",
    "fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_fused_prepacked",
    "fused_wqa_wkv_compressor_kv_score_indexer_compressor_kv_score_indexer_weights_proj_qkv_rmsnorm_fused_prepacked",
    "get_acl_affinity",
    "get_sdpa_version",
    "bf16_tiled_fused_moe",
    "bf16_tiled_fused_moe_scheduled",
    "bf16_tiled_fused_moe_async",
    "bf16_tiled_fused_moe_async_plan",
    "bf16_tiled_fused_moe_planned_staged",
    "bf16_tiled_fused_moe_vllm_staged",
    "bf16_linear",
    "bf16_linear_mm",
    "bf16_linear_raw",
    "has_cpp_kernels",
    "i8gemm",
    "kai_gemm",
    "kai_gemm_prepare",
    "multi_query_attention",
    "multi_query_attention_torch",
    "naive_fused_moe",
    "prepare_deepseek_v4_attn_gemm_weights",
    "prepare_deepseek_v4_inv_rope_woa",
    "prepare_bf16_linear_weight",
    "PostGemmStageVariant",
    "PreparedDeepSeekV4PostGemmW8A8Weights",
    "PreparedDeepSeekV4W8A8LinearWeight",
    "_HAS_DEEPSEEK_V4_W8A8",
    "_HAS_DEEPSEEK_V4_POST_GEMM_C128A_PREPACKED",
    "_HAS_DEEPSEEK_V4_POST_GEMM_DENSE_PREPACKED",
    "post_gemm_parallel_stage",
    "post_gemm_parallel_stage_cpp",
    "post_gemm_parallel_stage_cpp_prepacked",
    "post_gemm_parallel_stage_torch_baseline",
    "deepseek_v4_w8a8_linear",
    "deepseek_v4_w8a8_linear_pair",
    "deepseek_v4_wo_b_w8a8",
    "prepare_deepseek_v4_post_gemm_weights",
    "prepare_deepseek_v4_post_gemm_w8a8_quantized_weights",
    "prepare_deepseek_v4_post_gemm_w8a8_weights",
    "prepare_deepseek_v4_w8a8_linear_quantized_weight",
    "prepare_deepseek_v4_w8a8_linear_weight",
    "prepare_fused_moe_bf16_tiled_weights",
    "prepare_fused_moe_w8a16_tiled_weights",
    "prepare_fused_moe_w8a16_tiled_quantized_weights",
    "prepare_fused_moe_w8a8_tiled_weights",
    "prepare_fused_moe_w8a8_tiled_quantized_weights",
    "prepare_routed_shared_moe_bf16_tiled_weights",
    "prepare_routed_shared_moe_w8a16_tiled_quantized_weights",
    "prepare_shared_mlp_bf16_tiled_weights",
    "prepare_bf16_tiled_fused_moe_weights",
    "register_sdpa_version",
    "scaled_dot_product_attention",
    "sdpa_versioned",
    "set_acl_affinity",
    "set_default_moe_planner_runtime",
    "sparse_attn_indexer_op",
    "sparse_mla",
    "sparse_mla_naive",
    "upgrade_legacy_async_plan",
    "unpack_awq_qweight",
    "unpack_awq_qzeros",
    "w4a8_linear",
]
